import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

/** Barra navegação estilo Google (verde escuro). */
export const NAV_STRIP_BG = '#0F5132';

export function createActiveRideStyles(c: ThemeColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    map: { ...StyleSheet.absoluteFillObject },
    /** Faixa superior navegação (instrução + chips numa linha). */
    navStrip: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 22,
      backgroundColor: NAV_STRIP_BG,
      paddingHorizontal: 8,
      paddingBottom: 8,
    },
    navStripRow: {
      flexDirection: 'row',
      alignItems: 'center',
      minHeight: 48,
      gap: 8,
    },
    navBackBtn: {
      width: 40,
      height: 40,
      borderRadius: 20,
      alignItems: 'center',
      justifyContent: 'center',
    },
    navInstruction: {
      flex: 1,
      color: '#FFFFFF',
      fontSize: 14,
      fontWeight: '700',
      letterSpacing: 0.2,
    },
    navChipsInline: { flexDirection: 'row', alignItems: 'center', flexShrink: 0, gap: 6 },
    navChipCompact: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 4,
      paddingHorizontal: 8,
      paddingVertical: 5,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.14)',
    },
    navChipTextLight: { fontSize: 11, fontWeight: '800', color: '#FFFFFF' },
    navSecondaryLine: {
      paddingLeft: 48,
      paddingRight: 12,
      paddingBottom: 4,
    },
    navSecondaryText: {
      fontSize: 12,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.88)',
    },
    mapLoadingOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0,0,0,0.12)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 5,
    },
    /** Contêiner centrado — `top` passado no ecrã (safe area). */
    routeLoadingOuter: {
      position: 'absolute',
      left: 0,
      right: 0,
      alignItems: 'center',
      zIndex: 8,
    },
    /** Skeleton leve enquanto a polyline da corrida ainda não chegou. */
    routeLoadingPill: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 10,
      paddingHorizontal: 16,
      paddingVertical: 10,
      borderRadius: 20,
      backgroundColor: 'rgba(255,255,255,0.94)',
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.12,
          shadowRadius: 4,
        },
        android: { elevation: 3 },
      }),
    },
    routeLoadingText: {
      fontSize: 13,
      fontWeight: '700',
      color: c.text,
    },
    topBar: {
      position: 'absolute',
      top: 0,
      left: 0,
      right: 0,
      zIndex: 20,
      flexDirection: 'row',
      alignItems: 'flex-start',
      justifyContent: 'space-between',
      paddingHorizontal: 12,
    },
    backBtn: {
      width: 44,
      height: 44,
      borderRadius: 22,
      backgroundColor: c.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.12,
          shadowRadius: 6,
        },
        android: { elevation: 4 },
      }),
    },
    chipsRow: { flex: 1, flexDirection: 'row', justifyContent: 'flex-end', flexWrap: 'wrap', gap: 6 },
    chip: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 5,
      paddingHorizontal: 10,
      paddingVertical: 8,
      borderRadius: 16,
      backgroundColor: c.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    chipText: { fontSize: 11, fontWeight: '800', color: c.text },
    chipMuted: { fontSize: 8, fontWeight: '700', color: c.textMuted, textTransform: 'uppercase' },
    bottomSheet: {
      position: 'absolute',
      left: 0,
      right: 0,
      bottom: 0,
      backgroundColor: c.modalBg,
      borderTopLeftRadius: 24,
      borderTopRightRadius: 24,
      paddingHorizontal: 16,
      paddingTop: 8,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: -4 },
          shadowOpacity: 0.15,
          shadowRadius: 12,
        },
        android: { elevation: 16 },
      }),
    },
    handle: {
      alignSelf: 'center',
      width: 36,
      height: 4,
      borderRadius: 2,
      backgroundColor: c.border,
      marginBottom: 10,
    },
    rowActions: { flexDirection: 'row', gap: 10, marginBottom: 10 },
    callBtn: {
      flex: 1,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: c.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      flexDirection: 'row',
      gap: 6,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    callBtnText: { fontSize: 14, fontWeight: '800', color: c.text },
    primaryBtn: {
      flex: 2,
      paddingVertical: 14,
      borderRadius: 14,
      backgroundColor: c.accent,
      alignItems: 'center',
      justifyContent: 'center',
    },
    primaryBtnDanger: { backgroundColor: '#DC2626' },
    primaryBtnText: { fontSize: 15, fontWeight: '800', color: c.onAccent },
    statusStrip: {
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: c.surfaceElevated,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      marginBottom: 8,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    statusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: c.accent },
    statusText: { fontSize: 13, fontWeight: '800', color: c.textSecondary },
    /** Faixa compacta — chamada de voz pela internet. */
    internetCallBanner: {
      marginBottom: 10,
      paddingVertical: 10,
      paddingHorizontal: 12,
      borderRadius: 14,
      backgroundColor: c.accentMuted,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    internetCallBannerRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 10,
    },
    internetCallLabel: {
      flex: 1,
      fontSize: 13,
      fontWeight: '800',
      color: c.text,
    },
    internetCallSub: {
      fontSize: 11,
      fontWeight: '600',
      color: c.textMuted,
      marginTop: 2,
    },
    internetCallHangup: {
      paddingVertical: 8,
      paddingHorizontal: 12,
      borderRadius: 10,
      backgroundColor: '#DC2626',
    },
    internetCallHangupText: { fontSize: 12, fontWeight: '900', color: '#FFF' },
    internetCallDismiss: {
      paddingVertical: 6,
      paddingHorizontal: 10,
      borderRadius: 8,
      backgroundColor: c.surfaceElevated,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    internetCallDismissText: { fontSize: 12, fontWeight: '800', color: c.accent },
    callOptionsOverlay: {
      flex: 1,
      backgroundColor: 'rgba(0,0,0,0.45)',
      justifyContent: 'flex-end',
      padding: 16,
    },
    callOptionsSheet: {
      borderRadius: 20,
      paddingVertical: 8,
      paddingHorizontal: 4,
      backgroundColor: c.modalBg,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
    },
    callOptionsTitle: {
      fontSize: 13,
      fontWeight: '800',
      color: c.textMuted,
      textAlign: 'center',
      paddingVertical: 10,
      textTransform: 'uppercase',
      letterSpacing: 0.6,
    },
    callOptionsBtn: {
      paddingVertical: 14,
      paddingHorizontal: 16,
      borderRadius: 12,
      marginHorizontal: 8,
      marginVertical: 4,
      backgroundColor: c.surfaceElevated,
    },
    callOptionsBtnPrimary: {
      backgroundColor: c.accentMuted,
    },
    callOptionsBtnText: { fontSize: 16, fontWeight: '800', color: c.text, textAlign: 'center' },
    callOptionsBtnTextPrimary: { color: c.accent },
    callOptionsCancel: { paddingVertical: 14, marginTop: 4 },
    callOptionsCancelText: { fontSize: 15, fontWeight: '800', color: c.textSecondary, textAlign: 'center' },
    loadingBox: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
    loadingLabel: { marginTop: 12, fontSize: 12, fontWeight: '700', color: c.textSecondary },
    recenterFab: {
      position: 'absolute',
      right: 14,
      zIndex: 12,
      width: 48,
      height: 48,
      borderRadius: 24,
      backgroundColor: c.surfaceElevated,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#000',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.14,
          shadowRadius: 6,
        },
        android: { elevation: 5 },
      }),
    },
  });
}
