import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

export function createActivationStyles(c: ThemeColors) {
  return StyleSheet.create({
    root: { flex: 1, backgroundColor: c.bg },
    center: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 24 },
    muted: { fontSize: 14, color: c.textSecondary, textAlign: 'center' },
    loadingText: { marginTop: 10, fontSize: 13, color: c.textSecondary },
    errTitle: { marginTop: 12, fontSize: 17, fontWeight: '600', color: c.text },
    linkBtn: { marginTop: 16, paddingVertical: 12, paddingHorizontal: 20 },
    linkBtnText: { color: c.accent, fontWeight: '600' },
    topBar: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 8,
      paddingVertical: 10,
      backgroundColor: c.bg,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    backBtn: { padding: 8 },
    topTitle: { fontSize: 17, fontWeight: '600', color: c.text },
    scrollInner: { paddingHorizontal: 16, paddingTop: 12, gap: 14 },
    bannerErr: {
      flexDirection: 'row',
      gap: 8,
      backgroundColor: c.dangerMuted,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    bannerErrText: { flex: 1, fontSize: 13, color: c.danger },
    bannerOk: {
      flexDirection: 'row',
      gap: 8,
      backgroundColor: c.successBg,
      padding: 12,
      borderRadius: 12,
      borderWidth: 1,
      borderColor: c.border,
    },
    bannerOkText: { flex: 1, fontSize: 13, color: c.success },
    statusCard: {
      flexDirection: 'row',
      gap: 12,
      padding: 16,
      borderRadius: 16,
      alignItems: 'flex-start',
    },
    statusOk: { backgroundColor: c.successBg },
    statusInfo: { backgroundColor: c.infoBg },
    statusErr: { backgroundColor: c.dangerMuted },
    statusWarn: { backgroundColor: c.warningBg },
    statusIconWrap: {
      width: 44,
      height: 44,
      borderRadius: 12,
      backgroundColor: c.surface,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statusTitle: { fontSize: 16, fontWeight: '600', color: c.text, marginBottom: 4 },
    statusDesc: { fontSize: 13, color: c.textSecondary, lineHeight: 18 },
    card: {
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 1 },
          shadowOpacity: 0.05,
          shadowRadius: 6,
        },
        android: { elevation: 2 },
      }),
    },
    cardHead: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 14 },
    cardHeadIcon: {
      width: 36,
      height: 36,
      borderRadius: 10,
      backgroundColor: c.accentMuted,
      alignItems: 'center',
      justifyContent: 'center',
    },
    cardTitle: { fontSize: 16, fontWeight: '600', color: c.text },
    cardHint: { fontSize: 12, color: c.textMuted, marginBottom: 12 },
    label: { fontSize: 12, fontWeight: '500', color: c.textSecondary, marginBottom: 6 },
    input: {
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      fontSize: 15,
      color: c.text,
      backgroundColor: c.inputBg,
    },
    inputLocked: { opacity: 0.65 },
    inputLike: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      borderWidth: 1,
      borderColor: c.inputBorder,
      borderRadius: 12,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: c.inputBg,
      marginBottom: 12,
    },
    inputText: { fontSize: 15, color: c.text },
    inputPlaceholder: { fontSize: 15, color: c.textMuted },
    catRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 14 },
    catChip: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: c.chipBg,
      borderWidth: 1,
      borderColor: c.border,
    },
    catChipOn: {
      backgroundColor: c.chipBgActive,
      borderColor: c.accent,
    },
    catChipText: { fontSize: 12, fontWeight: '500', color: c.textMuted },
    catChipTextOn: { color: c.accent, fontWeight: '600' },
    saveDark: {
      backgroundColor: c.buttonMutedStrong,
      paddingVertical: 14,
      borderRadius: 12,
      alignItems: 'center',
      marginTop: 4,
    },
    saveDarkText: { color: '#FFFFFF', fontSize: 15, fontWeight: '600' },
    docRow: {
      borderWidth: 1,
      borderColor: c.border,
      borderRadius: 12,
      padding: 12,
      marginBottom: 10,
      backgroundColor: c.inputBg,
    },
    docRowOk: {
      borderColor: c.accent,
      backgroundColor: c.accentMuted,
    },
    docRowTop: { flexDirection: 'row', alignItems: 'center', gap: 10 },
    docTitle: { fontSize: 14, fontWeight: '600', color: c.text },
    docStatus: { fontSize: 11, color: c.textMuted, marginTop: 2 },
    alterBtn: {
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderRadius: 10,
      backgroundColor: c.surface,
      borderWidth: 1,
      borderColor: c.border,
    },
    alterBtnText: { fontSize: 12, fontWeight: '600', color: c.textSecondary },
    docPreview: {
      width: '100%',
      height: 120,
      borderRadius: 10,
      marginTop: 10,
      backgroundColor: c.border,
    },
    submitBtn: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 8,
      backgroundColor: c.accent,
      paddingVertical: 15,
      borderRadius: 14,
      marginTop: 4,
    },
    submitBtnOff: { backgroundColor: c.chipBg },
    submitText: { fontSize: 16, fontWeight: '600', color: '#FFF' },
    submitTextOff: { color: c.textMuted },
    hintCenter: { textAlign: 'center', fontSize: 12, color: c.textMuted, marginTop: 8, lineHeight: 17 },
    primaryBtn: {
      marginTop: 16,
      backgroundColor: c.accent,
      paddingHorizontal: 24,
      paddingVertical: 12,
      borderRadius: 12,
    },
    primaryBtnText: { color: '#FFF', fontWeight: '600' },
    /** Raiz do modal (opaco → sheet por cima). */
    modalRoot: {
      flex: 1,
    },
    modalBackdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.overlay,
    },
    /** Alinha a folha na parte inferior com espaço seguro. */
    modalSheetSafe: { flex: 1, width: '100%', justifyContent: 'flex-end' },
    /** Empurra a folha ligeiramente (não colada à borte inferior). */
    modalSheetOuter: {
      width: '100%',
      paddingHorizontal: 16,
      paddingTop: 8,
      paddingBottom: 4,
    },
    /** Caixa com teto de 80% do ecrã; conteúdo com scroll. */
    modalList: {
      maxHeight: '80%',
      width: '100%',
      backgroundColor: c.modalBg,
      borderRadius: 16,
      overflow: 'hidden',
    },
    modalListTitle: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textMuted,
      paddingHorizontal: 16,
      paddingTop: 12,
      paddingBottom: 4,
    },
    modalScroll: {
      flexGrow: 0,
    },
    /** Padding extra no fim do scroll; SafeArea aplica insets exteriores. */
    modalScrollInner: {
      paddingBottom: 16,
    },
    modalItem: { paddingVertical: 14, paddingHorizontal: 16 },
    modalItemText: { fontSize: 16, color: c.text },
  });
}

export type ActivationStyles = ReturnType<typeof createActivationStyles>;
