import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

export function createPerfilStyles(c: ThemeColors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scroll: { flex: 1 },
    scrollContent: {
      paddingHorizontal: 16,
      paddingTop: 12,
    },
    centerBox: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    configTitle: { fontSize: 16, fontWeight: '600', color: c.text, textAlign: 'center' },
    configSub: { marginTop: 8, fontSize: 13, color: c.textMuted, textAlign: 'center', lineHeight: 18 },
    loadingLabel: { marginTop: 10, fontSize: 13, color: c.textSecondary, fontWeight: '500' },
    headerCard: {
      backgroundColor: c.surface,
      borderRadius: 18,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      paddingTop: 18,
      paddingBottom: 18,
      paddingHorizontal: 14,
      alignItems: 'center',
      marginBottom: 14,
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 8,
        },
        android: { elevation: 2 },
      }),
    },
    avatarPress: { alignItems: 'center' },
    avatarWrap: {
      width: 76,
      height: 76,
      borderRadius: 38,
      backgroundColor: c.accentMuted,
      borderWidth: 2,
      borderColor: c.borderSubtle,
      overflow: 'hidden',
      alignItems: 'center',
      justifyContent: 'center',
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 4 },
          shadowOpacity: 0.12,
          shadowRadius: 10,
        },
        android: { elevation: 4 },
      }),
    },
    avatarImg: { width: '100%', height: '100%' },
    avatarInitials: {
      fontSize: 22,
      fontWeight: '700',
      color: c.accent,
      letterSpacing: 0.5,
    },
    name: {
      marginTop: 12,
      fontSize: 20,
      fontWeight: '600',
      color: c.text,
      letterSpacing: -0.3,
      textAlign: 'center',
    },
    rowCenter: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      marginTop: 6,
      maxWidth: '100%',
    },
    phone: {
      fontSize: 14,
      fontWeight: '500',
      color: c.textSecondary,
    },
    mail: {
      fontSize: 12,
      fontWeight: '400',
      color: c.textMuted,
      flex: 1,
    },
    badgeWrap: { marginTop: 12, alignItems: 'center' },
    badge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 6,
      paddingHorizontal: 12,
      paddingVertical: 7,
      borderRadius: 999,
      maxWidth: '100%',
    },
    badgeOk: {
      backgroundColor: c.successBg,
    },
    badgeWarn: {
      backgroundColor: c.dangerMuted,
    },
    badgeInfo: {
      backgroundColor: c.infoBg,
    },
    badgeNeutral: {
      backgroundColor: c.warningBg,
    },
    badgeText: {
      fontSize: 10,
      fontWeight: '600',
      color: c.warning,
      letterSpacing: 0.35,
      textTransform: 'uppercase',
      flexShrink: 1,
    },
    badgeTextOk: {
      color: c.success,
    },
    badgeTextErr: {
      color: c.danger,
    },
    badgeTextInfo: {
      color: c.info,
    },
    errorBanner: {
      backgroundColor: c.dangerMuted,
      borderRadius: 12,
      padding: 12,
      marginBottom: 12,
      borderWidth: 1,
      borderColor: c.border,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: 8,
    },
    errorText: { flex: 1, fontSize: 12, color: c.danger, fontWeight: '500' },
    errorRetry: {
      paddingHorizontal: 10,
      paddingVertical: 6,
      backgroundColor: c.dangerMuted,
      borderRadius: 8,
    },
    errorRetryText: { fontSize: 10, fontWeight: '600', color: c.danger },
    walletCard: {
      borderRadius: 18,
      overflow: 'hidden',
      padding: 16,
      marginBottom: 14,
      backgroundColor: c.walletCardBg,
      ...Platform.select({
        ios: {
          shadowColor: c.walletCardBgEnd,
          shadowOffset: { width: 0, height: 6 },
          shadowOpacity: 0.18,
          shadowRadius: 12,
        },
        android: { elevation: 6 },
      }),
    },
    walletTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    walletKicker: {
      fontSize: 9,
      fontWeight: '600',
      color: 'rgba(255,255,255,0.65)',
      letterSpacing: 0.85,
      textTransform: 'uppercase',
    },
    walletValue: {
      marginTop: 4,
      fontSize: 21,
      fontWeight: '700',
      color: '#FFF',
      letterSpacing: -0.35,
      lineHeight: 26,
    },
    walletIconBox: {
      padding: 8,
      borderRadius: 12,
      backgroundColor: 'rgba(255,255,255,0.18)',
    },
    walletDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: 'rgba(255,255,255,0.18)',
      marginVertical: 12,
    },
    walletFooter: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
    },
    walletMin: {
      fontSize: 10,
      fontWeight: '500',
      color: 'rgba(255,255,255,0.72)',
      letterSpacing: 0.2,
    },
    photoPreviewOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    photoPreviewImg: {
      width: '100%',
      maxHeight: '85%',
      aspectRatio: 1,
      borderRadius: 4,
    },
    menuCard: {
      backgroundColor: c.surface,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 8,
        },
        android: { elevation: 2 },
      }),
    },
    menuRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 14,
    },
    menuRowBorder: {
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: c.border,
    },
    menuLeft: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      flex: 1,
      minWidth: 0,
    },
    menuIcon: {
      width: 40,
      height: 40,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    menuTextCol: {
      flex: 1,
      minWidth: 0,
    },
    menuTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: c.text,
    },
    menuSub: {
      marginTop: 2,
      fontSize: 12,
      fontWeight: '400',
      color: c.textMuted,
    },
    logoutRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 14,
      paddingHorizontal: 14,
      backgroundColor: c.dangerMuted,
    },
    logoutTitle: {
      fontSize: 15,
      fontWeight: '600',
      color: c.danger,
    },
    logoutSub: {
      marginTop: 2,
      fontSize: 12,
      fontWeight: '400',
      color: c.danger,
      opacity: 0.85,
    },
    modalOverlay: {
      flex: 1,
      backgroundColor: c.overlay,
      justifyContent: 'center',
      padding: 24,
    },
    modalSheet: {
      backgroundColor: c.modalBg,
      borderRadius: 18,
      padding: 22,
      alignItems: 'center',
    },
    modalIconCircle: {
      width: 56,
      height: 56,
      borderRadius: 28,
      backgroundColor: 'rgba(234,88,12,0.12)',
      alignItems: 'center',
      justifyContent: 'center',
      marginBottom: 12,
    },
    modalTitle: {
      fontSize: 18,
      fontWeight: '600',
      color: c.text,
      textAlign: 'center',
    },
    modalSub: {
      marginTop: 6,
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      marginBottom: 16,
    },
    modalBtnPrimary: {
      width: '100%',
      backgroundColor: '#25D366',
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: 'center',
      marginBottom: 10,
    },
    modalBtnPrimaryText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '600',
    },
    modalBtnGhost: {
      width: '100%',
      paddingVertical: 12,
      borderRadius: 14,
      borderWidth: 1,
      borderColor: c.border,
      alignItems: 'center',
    },
    modalBtnGhostText: {
      fontSize: 14,
      fontWeight: '600',
      color: c.textSecondary,
    },
    aboutBox: {
      width: '100%',
      backgroundColor: c.inputBg,
      borderRadius: 14,
      padding: 14,
      marginBottom: 16,
      alignItems: 'flex-start',
    },
    aboutKicker: {
      fontSize: 9,
      fontWeight: '600',
      color: c.textMuted,
      letterSpacing: 0.8,
      textTransform: 'uppercase',
    },
    aboutVal: {
      marginTop: 2,
      fontSize: 13,
      fontWeight: '600',
      color: c.textSecondary,
    },
    aboutCopy: {
      marginTop: 2,
      fontSize: 11,
      color: c.textMuted,
      lineHeight: 16,
    },
    modalBtnDark: {
      width: '100%',
      backgroundColor: c.accentDark,
      paddingVertical: 14,
      borderRadius: 14,
      alignItems: 'center',
    },
    modalBtnDarkText: {
      color: '#FFF',
      fontSize: 15,
      fontWeight: '600',
    },
  });
}

export type PerfilStyles = ReturnType<typeof createPerfilStyles>;
