import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

export function createSaldoStyles(c: ThemeColors) {
  return StyleSheet.create({
  root: {
    flex: 1,
    backgroundColor: c.bg,
  },
  scroll: { flex: 1 },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 2,
  },
  centerBox: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 24,
  },
  configTitle: { fontSize: 16, fontWeight: '600', color: c.text, textAlign: 'center' },
  configSub: { marginTop: 8, fontSize: 13, color: c.textSecondary, textAlign: 'center', lineHeight: 18 },
  loadingLabel: { marginTop: 10, fontSize: 13, color: c.textSecondary, fontWeight: '500' },
  headerRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBottom: 14,
  },
  pageTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: c.text,
    letterSpacing: -0.35,
  },
  pageSub: {
    marginTop: 3,
    fontSize: 10,
    fontWeight: '600',
    color: c.textSecondary,
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  headerActions: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  iconBtn: {
    padding: 8,
    borderRadius: 14,
    backgroundColor: c.chipBg,
  },
  iconBtnGreen: {
    padding: 8,
    borderRadius: 14,
    backgroundColor: c.accent,
    ...Platform.select({
      ios: {
        shadowColor: c.accent,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.18,
        shadowRadius: 5,
      },
      android: { elevation: 3 },
    }),
  },
  errorBanner: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: c.dangerMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    borderRadius: 14,
    padding: 12,
    marginBottom: 14,
  },
  errorText: { flex: 1, fontSize: 12, fontWeight: '600', color: c.danger },
  errorRetry: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: c.dangerMuted,
    borderRadius: 8,
  },
  errorRetryText: { fontSize: 9, fontWeight: '700', color: c.danger, letterSpacing: 0.5 },
  balanceCard: {
    borderRadius: 18,
    overflow: 'hidden',
    marginBottom: 12,
    backgroundColor: c.walletCardBg,
    ...Platform.select({
      ios: {
        shadowColor: '#0F5132',
        shadowOffset: { width: 0, height: 6 },
        shadowOpacity: 0.18,
        shadowRadius: 14,
      },
      android: { elevation: 6 },
    }),
  },
  balanceCardInner: {
    padding: 16,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  balanceTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
  },
  balanceKicker: {
    fontSize: 10,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.72)',
    letterSpacing: 1.4,
  },
  balanceValue: {
    marginTop: 5,
    fontSize: 24,
    fontWeight: '600',
    color: '#FFF',
    letterSpacing: -0.4,
  },
  cardIconWrap: {
    padding: 8,
    borderRadius: 11,
    backgroundColor: 'rgba(255,255,255,0.14)',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: 'rgba(255,255,255,0.2)',
  },
  balanceDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,0.22)',
    marginVertical: 14,
  },
  balanceBottom: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    gap: 10,
  },
  miniKicker: {
    fontSize: 9,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.65)',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
  },
  miniStrong: {
    marginTop: 3,
    fontSize: 15,
    fontWeight: '600',
    color: '#FFF',
    letterSpacing: -0.2,
  },
  accountStateCol: { alignItems: 'flex-end', flex: 1 },
  statusPill: {
    marginTop: 5,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    paddingHorizontal: 11,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: c.surface,
  },
  statusPillBad: {
    backgroundColor: c.danger,
  },
  statusPillText: {
    fontSize: 10,
    fontWeight: '600',
    color: c.accent,
    letterSpacing: 0.15,
    maxWidth: 148,
  },
  statusPillTextBad: { color: c.onAccent },
  statusDot: { width: 5, height: 5, borderRadius: 2.5 },
  statusDotOk: { backgroundColor: c.accent },
  statusDotBad: { backgroundColor: c.onAccent },
  primaryCta: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    backgroundColor: c.accent,
    paddingVertical: 12,
    borderRadius: 14,
    marginBottom: 14,
    ...Platform.select({
      ios: {
        shadowColor: c.accent,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.16,
        shadowRadius: 6,
      },
      android: { elevation: 4 },
    }),
  },
  ctaIconWrap: {
    width: 28,
    height: 28,
    borderRadius: 14,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryCtaText: {
    color: '#FFF',
    fontSize: 15,
    fontWeight: '600',
    letterSpacing: 0.2,
  },
  infoBox: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    backgroundColor: c.walletUiInfoBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.walletUiInfoBorder,
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 11,
    marginBottom: 16,
  },
  infoIconBox: {
    padding: 5,
    borderRadius: 10,
    backgroundColor: c.walletUiInfoIconBg,
    marginTop: 1,
  },
  infoTitle: {
    fontSize: 10,
    fontWeight: '700',
    color: c.walletUiInfoTitle,
    textTransform: 'uppercase',
    letterSpacing: 0.85,
    marginBottom: 5,
  },
  infoBody: {
    fontSize: 12,
    color: c.walletUiInfoBody,
    lineHeight: 18,
    fontWeight: '500',
  },
  infoHighlight: {
    color: c.accent,
    fontWeight: '700',
  },
  tabBar: {
    flexDirection: 'row',
    backgroundColor: c.walletUiTabTrack,
    borderRadius: 12,
    padding: 3,
    marginBottom: 14,
    gap: 3,
  },
  tabBtn: {
    flex: 1,
    paddingVertical: 9,
    borderRadius: 9,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabBtnOn: {
    backgroundColor: c.walletUiTabPill,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
      },
      android: { elevation: 2 },
    }),
  },
  tabBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: c.textMuted,
    letterSpacing: 0.4,
    textTransform: 'uppercase',
  },
  tabBtnTextOn: {
    color: c.text,
  },
  section: { marginBottom: 6 },
  sectionHead: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    flex: 1,
    marginRight: 8,
    fontSize: 12,
    fontWeight: '800',
    color: c.text,
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  countBadge: {
    backgroundColor: c.surface,
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
  },
  countBadgeText: {
    fontSize: 8,
    fontWeight: '700',
    color: c.textSecondary,
    letterSpacing: 0.35,
    textTransform: 'uppercase',
  },
  discountHead: { marginBottom: 10 },
  sectionSub: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: '600',
    color: c.textSecondary,
    letterSpacing: 0.45,
    textTransform: 'uppercase',
    lineHeight: 13,
  },
  emptyState: {
    alignItems: 'center',
    paddingVertical: 28,
    paddingHorizontal: 18,
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: c.border,
    backgroundColor: c.bgMuted,
  },
  emptyIconCircle: {
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: c.surface,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.borderSubtle,
    marginBottom: 10,
  },
  emptyTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: c.text,
    textAlign: 'center',
  },
  emptySub: {
    marginTop: 5,
    fontSize: 12,
    color: c.textSecondary,
    textAlign: 'center',
    lineHeight: 17,
    fontWeight: '400',
  },
  txCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: c.surface,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    gap: 8,
    ...Platform.select({
      ios: {
        shadowColor: '#0F172A',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.035,
        shadowRadius: 5,
      },
      android: { elevation: 1 },
    }),
  },
  txLeft: { flexDirection: 'row', alignItems: 'center', gap: 10, flex: 1, minWidth: 0 },
  txIcon: {
    padding: 8,
    borderRadius: 11,
  },
  txIconOk: { backgroundColor: c.accentMuted },
  txIconBad: { backgroundColor: c.dangerMuted },
  txIconPending: { backgroundColor: c.warningBg },
  txAmount: { fontSize: 15, fontWeight: '700', color: c.text, letterSpacing: -0.2 },
  txMethod: {
    marginTop: 2,
    fontSize: 10,
    fontWeight: '600',
    color: c.accent,
    textTransform: 'uppercase',
    letterSpacing: 0.25,
  },
  txDate: {
    marginTop: 3,
    fontSize: 11,
    fontWeight: '500',
    color: c.textSecondary,
    letterSpacing: 0,
  },
  statusBadge: {
    paddingHorizontal: 8,
    paddingVertical: 5,
    borderRadius: 8,
  },
  statusBadgeOk: { backgroundColor: c.accent },
  statusBadgeBad: { backgroundColor: c.danger },
  statusBadgePending: {
    backgroundColor: c.warningBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
  },
  statusBadgeLabel: { fontSize: 8, fontWeight: '700', letterSpacing: 0.35, textTransform: 'uppercase' },
  statusBadgeLabelOk: { color: c.onAccent },
  statusBadgeLabelBad: { color: c.onAccent },
  statusBadgeLabelPending: { color: c.warning },
  rateCard: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: c.infoBg,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    borderRadius: 14,
    padding: 12,
    marginBottom: 10,
  },
  rateLeft: { flexDirection: 'row', alignItems: 'center', gap: 9, flex: 1 },
  rateIcon: {
    padding: 8,
    borderRadius: 11,
    backgroundColor: 'rgba(59,130,246,0.18)',
  },
  rateKicker: {
    fontSize: 9,
    fontWeight: '700',
    color: c.info,
    letterSpacing: 0.45,
    textTransform: 'uppercase',
  },
  rateValue: {
    marginTop: 3,
    fontSize: 15,
    fontWeight: '700',
    color: c.info,
    letterSpacing: -0.15,
  },
  rateError: { marginTop: 3, fontSize: 11, color: c.danger, fontWeight: '600' },
  rateRefresh: { padding: 6, borderRadius: 999 },
  skeletonStack: { gap: 8 },
  skeletonCard: {
    height: 64,
    borderRadius: 14,
    backgroundColor: c.bgMuted,
  },
  discountErrorBox: {
    padding: 16,
    borderRadius: 16,
    backgroundColor: c.dangerMuted,
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: c.border,
    alignItems: 'center',
  },
  discountErrorText: { fontSize: 13, color: c.danger, fontWeight: '600', textAlign: 'center' },
  discountRetry: {
    marginTop: 8,
    fontSize: 11,
    fontWeight: '800',
    color: c.danger,
    textTransform: 'uppercase',
    letterSpacing: 0.5,
  },
  emptyStateSoft: {
    paddingVertical: 22,
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: c.border,
    backgroundColor: c.bgMuted,
  },
  emptySoftText: { fontSize: 12, fontWeight: '500', color: c.textSecondary },
  commTitle: { fontSize: 12, fontWeight: '700', color: c.text },
  commRef: { marginTop: 2, fontSize: 11, fontWeight: '600', color: c.textSecondary },
  commDate: {
    marginTop: 3,
    fontSize: 10,
    fontWeight: '500',
    color: c.textMuted,
    letterSpacing: 0,
  },
  commRight: { alignItems: 'flex-end' },
  commDebit: { fontSize: 13, fontWeight: '700', color: c.danger, letterSpacing: -0.2 },
  commBal: {
    marginTop: 3,
    fontSize: 9,
    fontWeight: '500',
    color: c.textSecondary,
    maxWidth: 128,
    textAlign: 'right',
    lineHeight: 12,
  },

  });
}
