import { StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

export function createSupportStyles(c: ThemeColors) {
  return StyleSheet.create({
    sectionLabel: {
      fontSize: 12,
      fontWeight: '700',
      letterSpacing: 0.6,
      color: c.textMuted,
      textTransform: 'uppercase',
      marginBottom: 10,
      marginTop: 4,
      paddingHorizontal: 4,
    },
    card: {
      backgroundColor: c.surface,
      borderRadius: 18,
      overflow: 'hidden',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      marginBottom: 14,
    },
    row: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingVertical: 16,
      paddingHorizontal: 16,
    },
    rowFirst: { paddingTop: 16 },
    rowBorder: {
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    rowLeft: { flexDirection: 'row', alignItems: 'center', gap: 14, flex: 1, minWidth: 0 },
    rowIcon: {
      width: 44,
      height: 44,
      borderRadius: 12,
      alignItems: 'center',
      justifyContent: 'center',
    },
    rowTextCol: { flex: 1, minWidth: 0 },
    rowTitle: { fontSize: 16, fontWeight: '600', color: c.text },
    rowSub: { marginTop: 3, fontSize: 13, color: c.textMuted },
    primaryBtn: {
      backgroundColor: c.accent,
      borderRadius: 14,
      paddingVertical: 15,
      alignItems: 'center',
      marginTop: 4,
      marginBottom: 4,
    },
    primaryBtnText: { color: '#FFF', fontSize: 16, fontWeight: '600' },
    secondaryRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 16,
      paddingHorizontal: 16,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
      gap: 14,
    },
    secondaryIcon: {
      width: 40,
      height: 40,
      borderRadius: 10,
      alignItems: 'center',
      justifyContent: 'center',
    },
    secondaryTitle: { fontSize: 15, fontWeight: '600', color: c.text },
    secondarySub: { fontSize: 12, color: c.textMuted, marginTop: 2 },
    ticketItem: {
      padding: 16,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    ticketTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'flex-start', marginBottom: 6 },
    ticketCategory: { fontSize: 15, fontWeight: '600', color: c.text, flex: 1, marginRight: 8 },
    ticketStatus: { fontSize: 12, fontWeight: '600', overflow: 'hidden' },
    ticketDate: { fontSize: 12, color: c.textMuted },
    ticketsToggleRow: {
      paddingVertical: 14,
      alignItems: 'center',
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: c.border,
    },
    ticketsToggleText: {
      fontSize: 15,
      fontWeight: '600',
      color: c.success,
    },
    emptyText: { textAlign: 'center', fontSize: 14, color: c.textMuted, paddingVertical: 20 },
    errorText: { color: c.danger, fontSize: 13, marginBottom: 8, paddingHorizontal: 4 },
    groupLabel: {
      fontSize: 12,
      fontWeight: '700',
      color: c.textSecondary,
      marginTop: 8,
      marginBottom: 8,
      paddingHorizontal: 4,
    },
    input: {
      backgroundColor: c.surface,
      borderRadius: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      padding: 16,
      fontSize: 15,
      color: c.text,
      minHeight: 140,
      textAlignVertical: 'top',
    },
    categoryPill: {
      alignSelf: 'flex-start',
      backgroundColor: c.accentMuted,
      paddingHorizontal: 12,
      paddingVertical: 6,
      borderRadius: 20,
      marginBottom: 12,
    },
    categoryPillText: { fontSize: 13, fontWeight: '600', color: c.accent },
    groupCard: { marginBottom: 12 },
  });
}

export type SupportStyles = ReturnType<typeof createSupportStyles>;
