import { Platform, StyleSheet } from 'react-native';
import type { ThemeColors } from '@/theme/types';

export function createViagensStyles(c: ThemeColors) {
  return StyleSheet.create({
    root: {
      flex: 1,
      backgroundColor: c.bg,
    },
    scroll: { flex: 1 },
    scrollContent: {
      paddingHorizontal: 18,
      paddingBottom: 20,
    },
    centerBox: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      padding: 24,
    },
    loadingText: { marginTop: 10, fontSize: 13, color: c.textSecondary, fontWeight: '500' },
    configTitle: { fontSize: 16, fontWeight: '600', color: c.text, textAlign: 'center' },
    configSub: {
      marginTop: 8,
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      fontWeight: '400',
      lineHeight: 18,
    },
    errTitle: { marginTop: 14, fontSize: 16, fontWeight: '600', color: c.text },
    errSub: {
      marginTop: 8,
      fontSize: 13,
      color: c.textMuted,
      textAlign: 'center',
      fontWeight: '400',
      lineHeight: 18,
    },
    retryBtn: {
      marginTop: 18,
      paddingHorizontal: 22,
      paddingVertical: 12,
      backgroundColor: c.accent,
      borderRadius: 999,
    },
    retryBtnText: { color: '#FFF', fontWeight: '600', fontSize: 11, letterSpacing: 0.8 },
    headerBlock: { marginBottom: 14, paddingTop: 2 },
    pageTitle: {
      fontSize: 17,
      fontWeight: '600',
      color: c.text,
      textAlign: 'center',
      letterSpacing: -0.25,
    },
    pageSub: {
      marginTop: 5,
      fontSize: 9,
      fontWeight: '500',
      color: c.textMuted,
      textAlign: 'center',
      letterSpacing: 1.4,
    },
    periodWrap: {
      flexDirection: 'row',
      backgroundColor: c.surface,
      borderRadius: 14,
      padding: 4,
      marginBottom: 16,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      gap: 3,
    },
    periodBtn: {
      flex: 1,
      paddingVertical: 9,
      borderRadius: 11,
      alignItems: 'center',
    },
    periodBtnOn: {
      backgroundColor: c.accent,
    },
    periodLabel: {
      fontSize: 10,
      fontWeight: '600',
      color: c.textMuted,
      letterSpacing: 0.5,
    },
    periodLabelOn: { color: '#FFF' },
    statsGrid: {
      flexDirection: 'row',
      gap: 10,
      marginBottom: 18,
      position: 'relative',
    },
    statsOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.listLoadingScrim,
      zIndex: 2,
      borderRadius: 18,
      alignItems: 'center',
      justifyContent: 'center',
    },
    statCard: {
      flex: 1,
      backgroundColor: c.surface,
      borderRadius: 16,
      paddingVertical: 12,
      paddingHorizontal: 12,
      alignItems: 'center',
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      justifyContent: 'center',
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.04,
          shadowRadius: 8,
        },
        android: { elevation: 2 },
      }),
    },
    statIconGreen: {
      padding: 7,
      borderRadius: 12,
      backgroundColor: c.accentMuted,
      marginBottom: 6,
    },
    statIconBlue: {
      padding: 7,
      borderRadius: 12,
      backgroundColor: c.infoBg,
      marginBottom: 6,
    },
    statKicker: {
      fontSize: 9,
      fontWeight: '500',
      color: c.textMuted,
      letterSpacing: 0.6,
      marginBottom: 3,
    },
    statValue: {
      fontSize: 16,
      fontWeight: '600',
      color: c.text,
      letterSpacing: -0.2,
    },
    listHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      marginBottom: 10,
      paddingHorizontal: 0,
    },
    listTitle: {
      fontSize: 10,
      fontWeight: '600',
      color: c.text,
      letterSpacing: 1,
      flex: 1,
    },
    badgeGreen: {
      backgroundColor: c.accentMuted,
      paddingHorizontal: 10,
      paddingVertical: 5,
      borderRadius: 999,
    },
    badgeGreenText: {
      fontSize: 9,
      fontWeight: '600',
      color: c.accent,
      letterSpacing: 0.5,
    },
    listArea: { position: 'relative', gap: 10 },
    listOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: c.listLoadingScrim,
      zIndex: 2,
      borderRadius: 18,
      alignItems: 'center',
      paddingTop: 28,
    },
    emptyBox: {
      borderWidth: 1.5,
      borderStyle: 'dashed',
      borderColor: c.border,
      borderRadius: 16,
      paddingVertical: 28,
      paddingHorizontal: 20,
      alignItems: 'center',
      backgroundColor: c.surface,
    },
    emptyText: {
      marginTop: 10,
      fontSize: 10,
      fontWeight: '600',
      color: c.textMuted,
      letterSpacing: 0.6,
      textAlign: 'center',
    },
    tripCard: {
      backgroundColor: c.surface,
      borderRadius: 16,
      padding: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: c.border,
      ...Platform.select({
        ios: {
          shadowColor: '#0F172A',
          shadowOffset: { width: 0, height: 2 },
          shadowOpacity: 0.05,
          shadowRadius: 10,
        },
        android: { elevation: 3 },
      }),
    },
    tripTop: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      marginBottom: 10,
    },
    tripLeft: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, flex: 1, minWidth: 0 },
    avatarSm: {
      width: 34,
      height: 34,
      borderRadius: 10,
      backgroundColor: c.inputBg,
      alignItems: 'center',
      justifyContent: 'center',
      borderWidth: 1,
      borderColor: c.border,
    },
    avatarSmText: { fontSize: 10, fontWeight: '600', color: c.textMuted },
    clientName: { fontSize: 13, fontWeight: '600', color: c.text },
    timeRow: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 3 },
    timeText: { fontSize: 11, fontWeight: '400', color: c.textMuted, letterSpacing: 0.2 },
    tripRight: { alignItems: 'flex-end' },
    priceText: { fontSize: 15, fontWeight: '600', color: c.accent, letterSpacing: -0.2 },
    paidBadge: {
      flexDirection: 'row',
      alignItems: 'center',
      gap: 3,
      marginTop: 3,
      backgroundColor: c.successBg,
      paddingHorizontal: 7,
      paddingVertical: 2,
      borderRadius: 999,
    },
    paidText: { fontSize: 8, fontWeight: '600', color: c.success, letterSpacing: 0.4 },
    routeMini: { paddingLeft: 2, gap: 8 },
    routeMiniRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 8 },
    dotSm: { width: 6, height: 6, borderRadius: 3, marginTop: 3 },
    dotBlue: { backgroundColor: '#3B82F6' },
    routeMiniText: { flex: 1, fontSize: 11, fontWeight: '400', color: c.textSecondary, lineHeight: 15 },
  });
}
